kind: PersistentVolume
apiVersion: v1
metadata:
  name: minio-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dluhmer/development/persistent-storage/minio"
