apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

  #type: NodePort
  #ports:
  #- name: http
  #  port: 9000
  #  targetPort: 9000
  #  nodePort: 30036
  #  protocol: TCP
