apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /persistent-storage/pachyderm-minio-storage/
  #storageClassName: local-storage  
  #local:
  #  path: /persistent-storage/pachyderm-minio-storage/
  
