kind: PersistentVolume
apiVersion: v1
metadata:
  name: pachyderm-etcd-pv
  labels:
    type: local
spec:
  storageClassName: etcd-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "PATH-TO-ETCD"
