{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "influxdb", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU ([[tag_host]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "Used ([[tag_host]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Received ([[tag_host]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" }
     ]
    },
    {
     "alias": "Sent ([[tag_host]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Host: [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "3" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "4" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "5" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "6" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory Consumption of Cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "Used ([[tag_host]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  }
 ]
}